---
- name: Install RPM package on OpenShift nodes using rpm-ostree
  hosts: all
  become: true
  remote_user: core
  tasks:
    - name: Store RPM full path in a registry
      stat:
        path: "{{ rpm_full_path }}"
      register: rpm_file
      delegate_to: localhost
      run_once: true

    - name: Fail if RPM file does not exist
      fail:
        msg: "RPM file '{{ rpm_full_path }}' not found."
      when: not rpm_file.stat.exists

    - name: Copy RPM file to nodes
      copy:
        src: "{{ rpm_full_path }}"
        dest: /var/home/core/
        owner: core
        group: core
      register: copy_result

    - name: Install RPM package using rpm-ostree
      command: rpm-ostree -C override replace /var/home/core/{{ rpm_package }}
      register: rpm_ostree_result
      async: 600  # 10 minutes timeout
      poll: 30    # check every 30 seconds

    - name: Display rpm-ostree command output
      debug:
        msg: |
          Command: {{ rpm_ostree_result.cmd }}
          Return code: {{ rpm_ostree_result.rc }}
          STDOUT: {{ rpm_ostree_result.stdout }}
          STDERR: {{ rpm_ostree_result.stderr }}
      when: rpm_ostree_result is defined

    - name: Reboot nodes to apply changes
      reboot:
        msg: "Rebooting node to apply rpm-ostree changes"
        connect_timeout: 5
        reboot_timeout: 600  # Extended timeout for ostree boot
        pre_reboot_delay: 10
        post_reboot_delay: 60  # Wait longer after reboot
        test_command: podman exec etcd etcdctl member list
      throttle: 1  # Reboot one node at a time

  vars:
    rpm_full_path: "{{ rpm_full_path | default(lookup('env', 'RPM_FULL_PATH')) }}"
    rpm_package: "{{ rpm_full_path | basename }}"

