- name: Check for dev_scripts_path
  fail:
    msg: dev_scripts_path must be defined
  when: dev_scripts_path is undefined
- name: Stop OpenShift
  make:
    chdir: "{{dev_scripts_path}}"
    target: clean
- name: Reset dev-scripts checkout
  command: git reset --hard origin/master
  args:
    chdir: "{{dev_scripts_path}}"
