- name: Check for dev_scripts_path
  fail:
    msg: dev_scripts_path must be defined
  when: dev_scripts_path is undefined
- name: Stop OpenShift
  make:
    chdir: "{{dev_scripts_path}}"
    target: clean
- name: Reset dev-scripts checkout
  command: git reset --hard origin/{{dev_scripts_branch}}
  args:
    chdir: "{{dev_scripts_path}}"
- name: Remove /opt/dev-scripts directory completely
  file:
    path: /opt/dev-scripts
    state: absent
  become: true
