- name: Get username
  command: whoami
  register: whoami
- name: Enable user lingering
  command: loginctl enable-linger {{ whoami.stdout }}
  become: true
- name: Install SSH key
  authorized_key:
    user: "{{whoami.stdout}}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
- name: Install inputrc
  copy:
    dest: .inputrc
    content: |
      "\e[A":history-search-backward
      "\e[B":history-search-forward
- name: Set up for git user
  import_role:
    name: git-user
