- import_tasks: check_vars.yml
- name: Trigger set project
  assert:
    that: true
    quiet: true
  changed_when: true
  notify:
    - Set OCP project
- name: Start OpenShift
  make:
    chdir: "{{dev_scripts_path}}"
    target: "{{make_target[method]}}"
