- import_tasks: dev-scripts.yml
- name: Check for existing kubeconfig
  stat:
    path: "{{kubeconfig_path}}"
  register: kubeconfig
- import_tasks: create.yml
  when: not kubeconfig.stat.exists
- name: Setup oc aliases
  blockinfile:
    path: .bashrc
    validate: bash -e %s
    marker: "# {mark} OPENSHIFT ALIAS BLOCK"
    block: "{{ lookup('template', 'oc_aliases.sh.j2') }}"
- import_tasks: proxy.yml
