---
# Prerequisites check and installation for kcli-install

- name: Check if kcli is installed
  command: which kcli
  register: kcli_check
  failed_when: false
  changed_when: false

- name: Install kcli using dnf (RHEL/Fedora/CentOS)
  block:
    - name: Enable kcli copr repository
      command: dnf -y copr enable karmab/kcli
      become: true

    - name: Install kcli package
      dnf:
        name: kcli
        state: present
      become: true
  when: kcli_check.rc != 0

- name: Verify kcli installation
  command: which kcli
  register: kcli_verify
  failed_when: kcli_verify.rc != 0
  changed_when: false

- name: Check kcli version
  command: kcli version
  register: kcli_version_output
  changed_when: false

- name: Display kcli version
  debug:
    msg: "Using kcli version: {{ kcli_version_output.stdout }}"

# Use common authentication validation
- name: Validate authentication files
  include_role:
    name: common
    tasks_from: validate-auth

- name: Check available libvirt pools
  command: kcli list pool
  register: kcli_pools
  changed_when: false
  failed_when: false

- name: Display available pools
  debug:
    msg: "Available kcli pools: {{ kcli_pools.stdout_lines }}"

- name: Check available networks
  command: kcli list network
  register: kcli_networks
  changed_when: false
  failed_when: false

- name: Display available networks
  debug:
    msg: "Available kcli networks: {{ kcli_networks.stdout_lines }}" 